[devshell]
packages = []

[[commands]]
name = "darwin-MacBook"
category = "nix-darwin"
command = '''
        if [[ $(pwd) != "~/.config/nixpkgs/nixos-flk/hosts/MacBook" ]]; then
        cd ~/.config/nixpkgs/nixos-flk/hosts/MacBook
        darwin-rebuild $@ --flake .#MacBook
        fi
        '''
help = "darwin-MacBook rebuild"


[[commands]]
name = "ae"
category = "secrets"
command = "agenix -e $@"
help = "agenix edit file"


[[commands]]
name = "update"
category = "bumpup"
command = "nix flake lock --update-input $@"
help = "lock-update unstable"

[[env]]
name = "GC_DONT_GC" #https://github.com/NixOS/nix/issues/4178
value = "1"
