# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vscode-extensions-copilot = {
    pname = "vscode-extensions-copilot";
    version = "1.49.6911";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.49.6911/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.49.6911.zip";
      sha256 = "sha256-1wuUFvlet+BtXQtTXZbigfqh9hsAA4Yqr0yCA8CVw5o=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-indent-rainbow = {
    pname = "vscode-extensions-indent-rainbow";
    version = "8.3.1";
    src = fetchurl {
      url = "https://oderwat.gallery.vsassets.io/_apis/public/gallery/publisher/oderwat/extension/indent-rainbow/8.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "indent-rainbow-8.3.1.zip";
      sha256 = "sha256-dOicya0B2sriTcDSdCyhtp0Mcx5b6TUaFKVb0YU3jUc=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-julia-color-themes = {
    pname = "vscode-extensions-julia-color-themes";
    version = "0.1.1";
    src = fetchurl {
      url = "https://cameronbieganek.gallery.vsassets.io/_apis/public/gallery/publisher/cameronbieganek/extension/julia-color-themes/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "julia-color-themes-0.1.1.zip";
      sha256 = "sha256-22TA7RpC0W3G8uA4EIqeuB4gqDF9cr1gNS+u7qQ3IaA=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-language-julia = {
    pname = "vscode-extensions-language-julia";
    version = "1.7.12";
    src = fetchurl {
      url = "https://julialang.gallery.vsassets.io/_apis/public/gallery/publisher/julialang/extension/language-julia/1.7.12/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "language-julia-1.7.12.zip";
      sha256 = "sha256-g6os6ktSWzUSCnLzMkGRoOhCEvU3gXcGGj2cq1NKkaE=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-language-rust = {
    pname = "vscode-extensions-language-rust";
    version = "0.7.8";
    src = fetchurl {
      url = "https://rust-lang.gallery.vsassets.io/_apis/public/gallery/publisher/rust-lang/extension/rust/0.7.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "rust-0.7.8.zip";
      sha256 = "sha256-Y33agSNMVmaVCQdYd5mzwjiK5JTZTtzTkmSGTQrSNg0=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-markdown-preview-enhanced = {
    pname = "vscode-extensions-markdown-preview-enhanced";
    version = "0.6.3";
    src = fetchurl {
      url = "https://shd101wyy.gallery.vsassets.io/_apis/public/gallery/publisher/shd101wyy/extension/markdown-preview-enhanced/0.6.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-preview-enhanced-0.6.3.zip";
      sha256 = "sha256-dCWERQ5rHnmYLtYl12gJ+dXLnpMu55WnmF1VfdP0x34=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-multi-cursor-case-preserve = {
    pname = "vscode-extensions-multi-cursor-case-preserve";
    version = "1.0.5";
    src = fetchurl {
      url = "https://Cardinal90.gallery.vsassets.io/_apis/public/gallery/publisher/Cardinal90/extension/multi-cursor-case-preserve/1.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "multi-cursor-case-preserve-1.0.5.zip";
      sha256 = "sha256-eJafjYDydD8DW83VLH9MPFeDENXBx3el7XvjZqu88Jw=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-nickel-syntax = {
    pname = "vscode-extensions-nickel-syntax";
    version = "0.0.1";
    src = fetchurl {
      url = "https://kubukoz.gallery.vsassets.io/_apis/public/gallery/publisher/kubukoz/extension/nickel-syntax/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nickel-syntax-0.0.1.zip";
      sha256 = "sha256-eti0BGhehQJIdKwwsY/lNxQdlffe0dqvFKvNJFGxHwQ=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-pdf = {
    pname = "vscode-extensions-pdf";
    version = "1.2.0";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.0.zip";
      sha256 = "sha256-/2u2yfAmSVBvfXIMt2VokkeYH8q8Y9Ca9YSDuwwpkq0=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-readable-indent = {
    pname = "vscode-extensions-readable-indent";
    version = "1.2.2";
    src = fetchurl {
      url = "https://cnojima.gallery.vsassets.io/_apis/public/gallery/publisher/cnojima/extension/readable-indent/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "readable-indent-1.2.2.zip";
      sha256 = "sha256-iTgbxasaNTIBlLLUPs00Y9x099zfXc6ES6drTc8CE78=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-rust-analyzer = {
    pname = "vscode-extensions-rust-analyzer";
    version = "0.4.1232";
    src = fetchurl {
      url = "https://rust-lang.gallery.vsassets.io/_apis/public/gallery/publisher/rust-lang/extension/rust-analyzer/0.4.1232/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "rust-analyzer-0.4.1232.zip";
      sha256 = "sha256-1+hgt/HIu3tAuPC8+cGNFw7yfxAOjsdYhNGBR3gMvpM=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-tokyo-night = {
    pname = "vscode-extensions-tokyo-night";
    version = "0.9.4";
    src = fetchurl {
      url = "https://enkia.gallery.vsassets.io/_apis/public/gallery/publisher/enkia/extension/tokyo-night/0.9.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tokyo-night-0.9.4.zip";
      sha256 = "sha256-pKokB6446SR6LsTHyJtQ+FEA07A0W9UAI+byqtGeMGw=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-vscode-direnv = {
    pname = "vscode-extensions-vscode-direnv";
    version = "0.6.1";
    src = fetchurl {
      url = "https://mkhl.gallery.vsassets.io/_apis/public/gallery/publisher/mkhl/extension/direnv/0.6.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "direnv-0.6.1.zip";
      sha256 = "sha256-5/Tqpn/7byl+z2ATflgKV1+rhdqj+XMEZNbGwDmGwLQ=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-vscode-emacs-friendly = {
    pname = "vscode-extensions-vscode-emacs-friendly";
    version = "0.9.0";
    src = fetchurl {
      url = "https://lfs.gallery.vsassets.io/_apis/public/gallery/publisher/lfs/extension/vscode-emacs-friendly/0.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-friendly-0.9.0.zip";
      sha256 = "sha256-YWu2a5hz0qGZvgR95DbzUw6PUvz17i1o4+eAUM/xjMg=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-vscode-markdownlint = {
    pname = "vscode-extensions-vscode-markdownlint";
    version = "0.48.1";
    src = fetchurl {
      url = "https://DavidAnson.gallery.vsassets.io/_apis/public/gallery/publisher/DavidAnson/extension/vscode-markdownlint/0.48.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.48.1.zip";
      sha256 = "sha256-3TpZGvas+pfabHayaA6Yd9nOO2MbfXbCvCiTcbja9Vo=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-zeek = {
    pname = "vscode-extensions-zeek";
    version = "0.6.0";
    src = fetchurl {
      url = "https://aeppert.gallery.vsassets.io/_apis/public/gallery/publisher/aeppert/extension/bro/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bro-0.6.0.zip";
      sha256 = "sha256-+wISGCtGq/l058dOaAKlD3pGknP2ksekS1Rgmax5QgU=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
}
