logging:
  console: true
  console_verbosity: DEBUG
  file: false
  file_verbosity: DEBUG
  filename: threatbus.log

plugins:
  backbones:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      vhost: /
      exchange_name: threatbus
      queue:
        name_suffix: "my_suffix" # optional. remove property / set empty to use 'hostname'
        name_join_symbol: . # queue will be named "threatbus" + join_symbol + name_suffix
        durable: true
        auto_delete: false
        lazy: true
        exclusive: false
        max_items: 100000 # optional. remove property / set to 0 to allow infinite length

  apps:
    zeek:
      host: "127.0.0.1"
      port: 47761
      module_namespace: Tenzir
    misp:
      api:
        host: https://localhost
        ssl: false
        key: MISP_API_KEY
      filter: # filter are optional. you can omit the entire section.
        - orgs: # org IDs must be strings: https://github.com/MISP/PyMISP/blob/main/pymisp/data/schema.json
            - "1"
            - "25"
          tags:
            - "TLP:AMBER"
            - "TLP:RED"
          types: # MISP attribute types https://github.com/MISP/misp-objects/blob/main/schema_objects.json
            - ip-src
            - ip-dst
            - hostname
            - domain
            - url
      zmq:
        host: localhost
        port: 50000
      #kafka:
      #  topics:
      #  - misp_attribute
      #  poll_interval: 1.0
      #  # All config entries are passed as-is to librdkafka
      #  # https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
      #  config:
      #    bootstrap.servers: "localhost:9092"
      #    group.id: "threatbus"
      #    auto.offset.reset: "earliest"
    zmq-app:
      host: "127.0.0.1"
      manage: 13370 # the port used for management messages
      pub: 13371 # the port used to publish messages to connected apps
      sub: 13372 # the port used to receive messages from connected apps
    cif3:
      api:
        host: http://localhost:5000
        ssl: false
        token: CIF_TOKEN
      group: everyone
      confidence: 7.5
      tlp: amber
      tags:
        - test
        - malicious
