# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  kitty-darwin = {
    pname = "kitty-darwin";
    version = "0.26.3";
    src = fetchurl {
      url = "https://github.com/kovidgoyal/kitty/releases/download/v0.26.3/kitty-0.26.3.dmg";
      sha256 = "sha256-slgdXB8I1cZxjcSFDM/DA1RYjdkPeoG8RsVDacxyXVA=";
    };
  };
  logseq = {
    pname = "logseq";
    version = "0.8.7";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.7/logseq-linux-x64-0.8.7.AppImage";
      sha256 = "sha256-FMGNaA/a1IzF2T0k9LGCOvLK26SlxX2cCOn7dLD/o7c=";
    };
  };
  logseq-darwin = {
    pname = "logseq-darwin";
    version = "0.8.7";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.8.7/logseq-darwin-x64-0.8.7.dmg";
      sha256 = "sha256-l/ey7DJL2e7HuH3g+cFMGdWFxCRgoibDC57XJr8/KV4=";
    };
  };
}
