# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20220503";
    src = fetchurl {
      url = "https://pypi.io/packages/source/H/HPI/HPI-0.3.20220503.tar.gz";
      sha256 = "sha256-7wDO/nFSGM7sbFhNTDhdx8ned/hCEWEJQNUL7phearQ=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "c8ed1f1f0bbd59eb5e152406541e9813feed4873";
    src = fetchFromGitHub ({
      owner = "StevenBlack";
      repo = "hosts";
      rev = "c8ed1f1f0bbd59eb5e152406541e9813feed4873";
      fetchSubmodules = false;
      sha256 = "sha256-Lyw7A9ElYkGHLvTgB2QzDJ+Jwpqy20OUIv14XUEWZ0k=";
    });
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.6";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.6/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-nPcqAk0m1e9izkylBuNcatHESgvSewR+MKmVdz+HBec=";
    };
  };
  chord = {
    pname = "chord";
    version = "0.2.38";
    src = fetchurl {
      url = "https://github.com/PeterDing/chord/releases/download/v0.2.38/chord-0.2.38-linux-x86_64.AppImage";
      sha256 = "sha256-14rkxceyS0OwnOK14rICWnzLLkRB8dmqRkPq829znws=";
    };
  };
  drawio = {
    pname = "drawio";
    version = "18.0.6";
    src = fetchurl {
      url = "https://github.com/jgraph/drawio-desktop/releases/download/v18.0.6/drawio-x86_64-18.0.6.rpm";
      sha256 = "sha256-k50j9F+CvEl4/zy10V0Jb4r5ZY+5+SEdOEmZj2oL06k=";
    };
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  magnetw = {
    pname = "magnetw";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/xiandanin/magnetW/releases/download/3.1.1/magnetw-3.1.1-linux.AppImage";
      sha256 = "sha256-ie6XGdd/HQCxIaLY5gGOgOXCHDJxcnaxgaO7plA5Eh8=";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.6.11";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11.AppImage";
      sha256 = "sha256-tE2Q7NM+cQOg+vyqyfRwg05EOMQWhhggTA6S+VT+SkM=";
    };
  };
  notdeft = {
    pname = "notdeft";
    version = "1b7054dcfc3547a7cafeb621552cec01d0540478";
    src = fetchFromGitHub ({
      owner = "hasu";
      repo = "notdeft";
      rev = "1b7054dcfc3547a7cafeb621552cec01d0540478";
      fetchSubmodules = false;
      sha256 = "sha256-LMMLJFVpmoE/y3MqrgY2fmsehmzk6TkLsVoHmFUxiSw=";
    });
  };
  orgparse = {
    pname = "orgparse";
    version = "0.3.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/o/orgparse/orgparse-0.3.1.tar.gz";
      sha256 = "sha256-hg5vu5pnt0K6p5LmD4zBhSLpeJwGXSaCHAIoXV/BBK8=";
    };
  };
  polar-bookshelf = {
    pname = "polar-bookshelf";
    version = "2.0.103";
    src = fetchurl {
      url = "https://github.com/burtonator/polar-bookshelf/releases/download/v2.0.103/polar-desktop-app-2.0.103-amd64.deb";
      sha256 = "sha256-jcq0hW698bAhVM3fLQQeKAnld33XLkHsGjS3QwUpciQ=";
    };
  };
  polar-darwin = {
    pname = "polar-darwin";
    version = "2.0.103";
    src = fetchurl {
      url = "https://github.com/burtonator/polar-bookshelf/releases/download/v2.0.103/Polar-2.0.103.dmg";
      sha256 = "sha256-DCg5myqgcdOW9P7jq81QqDnfjwozlUq43gltZVjCrXI=";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "bc1a798386d3cd3b362b3c2d362498a2df2daae6";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "bc1a798386d3cd3b362b3c2d362498a2df2daae6";
      fetchSubmodules = false;
      sha256 = "sha256-/jwcogGRjJFaBqELZh30Nk0yE+0uX+htC1hod83wCms=";
    });
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "b3be570a8166d824c4b1e84f1fb3a21444338ff9";
    src = fetchFromGitHub ({
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "b3be570a8166d824c4b1e84f1fb3a21444338ff9";
      fetchSubmodules = false;
      sha256 = "sha256-WzECATaDst4xO4vCaYP+DL8t+9gm2sor1Q8OCzKHmKE=";
    });
  };
}
