# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vscode-extensions-indent-rainbow = {
    pname = "vscode-extensions-indent-rainbow";
    version = "8.2.2";
    src = fetchurl {
      url = "https://oderwat.gallery.vsassets.io/_apis/public/gallery/publisher/oderwat/extension/indent-rainbow/8.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-7kkJc+hhYaSKUbK4eYwOnLvae80sIg7rd0E4YyCXtPc=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-julia-color-themes = {
    pname = "vscode-extensions-julia-color-themes";
    version = "0.1.1";
    src = fetchurl {
      url = "https://cameronbieganek.gallery.vsassets.io/_apis/public/gallery/publisher/cameronbieganek/extension/julia-color-themes/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-22TA7RpC0W3G8uA4EIqeuB4gqDF9cr1gNS+u7qQ3IaA=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-language-julia = {
    pname = "vscode-extensions-language-julia";
    version = "1.5.6";
    src = fetchurl {
      url = "https://julialang.gallery.vsassets.io/_apis/public/gallery/publisher/julialang/extension/language-julia/1.5.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-gThEwb7Ng9tT9JlHHJ2zbTYQkCpubjfhJ853mPchNYk=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-markdown-preview-enhanced = {
    pname = "vscode-extensions-markdown-preview-enhanced";
    version = "0.6.1";
    src = fetchurl {
      url = "https://shd101wyy.gallery.vsassets.io/_apis/public/gallery/publisher/shd101wyy/extension/markdown-preview-enhanced/0.6.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-KssvqRk3IIBO/CJd1AN5w0vbj/16K63yn+f8iK/kjhs=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-multi-cursor-case-preserve = {
    pname = "vscode-extensions-multi-cursor-case-preserve";
    version = "1.0.5";
    src = fetchurl {
      url = "https://Cardinal90.gallery.vsassets.io/_apis/public/gallery/publisher/Cardinal90/extension/multi-cursor-case-preserve/1.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-eJafjYDydD8DW83VLH9MPFeDENXBx3el7XvjZqu88Jw=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-nickel-syntax = {
    pname = "vscode-extensions-nickel-syntax";
    version = "0.0.1";
    src = fetchurl {
      url = "https://kubukoz.gallery.vsassets.io/_apis/public/gallery/publisher/kubukoz/extension/nickel-syntax/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-eti0BGhehQJIdKwwsY/lNxQdlffe0dqvFKvNJFGxHwQ=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-pdf = {
    pname = "vscode-extensions-pdf";
    version = "1.1.0";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-a+uHSyh1ne1C1cKdfPXC+mD3282Cp4ocAY7sc3wkml0=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-readable-indent = {
    pname = "vscode-extensions-readable-indent";
    version = "1.2.2";
    src = fetchurl {
      url = "https://cnojima.gallery.vsassets.io/_apis/public/gallery/publisher/cnojima/extension/readable-indent/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-iTgbxasaNTIBlLLUPs00Y9x099zfXc6ES6drTc8CE78=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-tabnine-vscode = {
    pname = "vscode-extensions-tabnine-vscode";
    version = "3.5.1";
    src = fetchurl {
      url = "https://TabNine.gallery.vsassets.io/_apis/public/gallery/publisher/TabNine/extension/tabnine-vscode/3.5.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-zP16zX/VT3tWmvlJZHjCjO42R0jdLTBUtT0dsrRPlBo=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-tokyo-night = {
    pname = "vscode-extensions-tokyo-night";
    version = "0.8.2";
    src = fetchurl {
      url = "https://enkia.gallery.vsassets.io/_apis/public/gallery/publisher/enkia/extension/tokyo-night/0.8.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-q9QKbMYSOY4u7Aao5oh1ykH34QNJ76ZASBZqwq8ynIk=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-vscode-emacs-friendly = {
    pname = "vscode-extensions-vscode-emacs-friendly";
    version = "0.9.0";
    src = fetchurl {
      url = "https://lfs.gallery.vsassets.io/_apis/public/gallery/publisher/lfs/extension/vscode-emacs-friendly/0.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-YWu2a5hz0qGZvgR95DbzUw6PUvz17i1o4+eAUM/xjMg=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-vscode-markdownlint = {
    pname = "vscode-extensions-vscode-markdownlint";
    version = "0.45.0";
    src = fetchurl {
      url = "https://DavidAnson.gallery.vsassets.io/_apis/public/gallery/publisher/DavidAnson/extension/vscode-markdownlint/0.45.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-L7y+Lsx1DMS12JtxSl7WkT8jGQLipebNKxknF/Y1ke0=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
  vscode-extensions-zeek = {
    pname = "vscode-extensions-zeek";
    version = "0.6.0";
    src = fetchurl {
      url = "https://aeppert.gallery.vsassets.io/_apis/public/gallery/publisher/aeppert/extension/bro/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "sha256-+wISGCtGq/l058dOaAKlD3pGknP2ksekS1Rgmax5QgU=";
    };
    homepage = "none";
    license = "mit";
    description = "none";
  };
}
