[aws]
symbol = " "

[character]
success_symbol = "[λ](bold blue) "
vicmd_symbol = "[V](bold green) "
error_symbol = "[λ](bold red) "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[directory]
style = "cyan"
read_only = " 🔒"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold dimmed white"

[git_status]
conflicted = "⚠️"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "
disabled = false

[nim]
symbol = " "

[nix_shell]
format = 'via [☃️ $state( \($name\))](bold blue) '
symbol = " "
impure_msg = "impure"
pure_msg = "λ"
style = "cyan"

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
disabled = false
