# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20210220";
    src = fetchurl {
      url = "https://pypi.io/packages/source/H/HPI/HPI-0.3.20210220.tar.gz";
      sha256 = "0i1fh3lkiwwggr0p9l9nvw8a8lxmgslkd90dxm1h4cqpsbckdvln";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "8f1d4f2f34c523562e60621c43a1b9f70c63ec42";
    src = fetchgit {
      url = "https://github.com/StevenBlack/hosts";
      rev = "8f1d4f2f34c523562e60621c43a1b9f70c63ec42";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0myx6xmcmsk77dl5655v77fb0cwxk695r64c7yim7lj8880pn6av";
    };
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.106.3";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.106.3/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "11p081dqilga61zfziw5w37k6v2r84qynhz2hr4gk8367jck54x8";
    };
  };
  chord = {
    pname = "chord";
    version = "0.2.38";
    src = fetchurl {
      url = "https://github.com/PeterDing/chord/releases/download/v0.2.38/chord-0.2.38-linux-x86_64.AppImage";
      sha256 = "02wzfdpz7sj38smdkwa18hpcnz2s0arf5dg2kjq46jxjqz2y92np";
    };
  };
  logseq = {
    pname = "logseq";
    version = "0.4.1";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.4.1/logseq-linux-x64-0.4.1.AppImage";
      sha256 = "0b8b8hzm96nh7s6pf7mv2k5y1s79glvm3g6c934cvc4ag24ds9cz";
    };
  };
  logseq-darwin = {
    pname = "logseq-darwin";
    version = "0.4.1";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.4.1/logseq-darwin-x64-0.4.1.dmg";
      sha256 = "17kyzsm8qdnk9hjv8iwybb9wms6gnrbw1pr57dy3mqpk8xcailv7";
    };
  };
  magnetw = {
    pname = "magnetw";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/xiandanin/magnetW/releases/download/3.1.1/magnetw-3.1.1-linux.AppImage";
      sha256 = "07qj758adfx3h6qpcwki68fc5rc0iq0ydn5246qh07bzswcrgvl9";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.6.11";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11.AppImage";
      sha256 = "0hsazragk4hf9hh1i1hnqhw48kl3f3sckapwzah06w9ysgn90kdl";
    };
  };
  notdeft = {
    pname = "notdeft";
    version = "9740eceae6929c62da81f9e19646412d01e88def";
    src = fetchgit {
      url = "https://github.com/hasu/notdeft";
      rev = "9740eceae6929c62da81f9e19646412d01e88def";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "064pcb57vg1hpkhg2k13bm9svl0ck0mmgf33q6v12za7vpc4bmkf";
    };
  };
  orgparse = {
    pname = "orgparse";
    version = "0.2.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/o/orgparse/orgparse-0.2.4.tar.gz";
      sha256 = "0x2dbdjnc9hb2l7hhr1zj78fxglnv81dsn1gsh0h56s5rw930v2v";
    };
  };
  polar-bookshelf = {
    pname = "polar-bookshelf";
    version = "2.0.103";
    src = fetchurl {
      url = "https://github.com/burtonator/polar-bookshelf/releases/download/v2.0.103/polar-desktop-app-2.0.103-amd64.deb";
      sha256 = "093j542l7drl3bn42bnpgmvya2983q22vpydahhv1wdxds2v9jld";
    };
  };
  polar-darwin = {
    pname = "polar-darwin";
    version = "2.0.103";
    src = fetchurl {
      url = "https://github.com/burtonator/polar-bookshelf/releases/download/v2.0.103/Polar-2.0.103.dmg";
      sha256 = "0wmdq9c6av89vsw4m59k1a7xyfd8a36spqzyyjbd6wd05adkja0c";
    };
  };
  promnesia = {
    pname = "promnesia";
    version = "bc9d9034aa7d83c12e24c60aac50c965513ef9ae";
    src = fetchgit {
      url = "https://github.com/karlicoss/promnesia";
      rev = "bc9d9034aa7d83c12e24c60aac50c965513ef9ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0993hc1bh2rlkdcqc9k39hr15fxdj27l0vqr9d9m3cq1rim22czz";
    };
  };
}
