[[snippets]]
  description = "shadowsocks lib"
  command = "ss-local -c ~/.config/ss/config.json"
  output = ""

[[snippets]]
  description = "cut zeek log"
  command = "cat <log> | zeek-cut <field>"
  output = ""

###vast
[[snippets]]
  description = "zeek|vast: import zeek logs to vast"
  command = "zcat <ZeekLogsPath/*.log.gz> | vast import zeek"
  output = ""

[[snippets]]
  description = "zeek|vast: export zeek logs filtered by addr "
  command = " vast export zeek ':addr in <addr>'"
  output = ""


[[snippets]]
  description = "docker: clean regex"
  command = "docker rmi (docker images --filter=reference='<regex>' -q)"
  output = ""

### deepsea
[[snippets]]
  description = "deepsea: Inline CSS with template"
  command = "deepsea --config template.yaml content inline"
  output = ""


[[snippets]]
  description = "deepsea: Create a TXT verson from the HTML version (.ttpl)"
  command = "deepsea --config template.yaml content multipart"
  output = ""


[[snippets]]
  description = "deepsea-Step1: create DB and createtable "
  command = "deepsea -t --config template.yaml storage -D template.db manager  -T createtable"
  output = "if this command failed, you can touch a db <name>.db file"

[[snippets]]
  description = "deepsea: load marks from CSV"
  command = "deepsea -t --config template.yaml "

[[snippets]]
  description = "deepsea: show the marks are loaded"
  command = "deepsea --config template.yaml  storage  -d template.db manager  -T showmarks"
  output = ""


[[snippets]]
  description = "deepsea: mailclient"
  command = "deepsea mailclient --config template.yaml"
  output = ""
