name: "CI"
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/cache@v2.1.6
      with:
        path: |
          path: /nix/store
        key: ${{ runner.os }}-nix-store

    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210415_76980a1/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix

    #- run: nix -Lv flake check
    - run: nix -Lv develop -c echo OK
