name: "CI"
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        install_url:
          https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.5pre20211026_5667822/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix

    #- run: nix -Lv flake check
    - run: nix -Lv develop -c echo OK
